/*
 * Explorateur Écocités
 * Copyright (C) 2019 l'État, ministère chargé du logement
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.efficacity.explorateurecocites.utils.enumeration;

import java.util.Optional;

public enum MAITRISE_OUVRAGE {
    ACTEURS_DE_L_ECOSYSTEME_NUMERIQUE("[mo_prefix_code]_acteurs_de_l_ecosysteme_numerique", "Acteurs de l’écosystème numérique"),
    ACTEURS_SOCIOCULTURELS("[mo_prefix_code]_acteurs_socioculturels", "Acteurs socioculturels"),
    ACTIS_OPH_DE_LA_REGION_GRENOBLOISE("[mo_prefix_code]_actis_oph_de_la_region_grenobloise", "Actis OPH de la région grenobloise"),
    AEROPORT_DE_MONTPELLIER("[mo_prefix_code]_aeroport_de_montpellier", "Aéroport de Montpellier"),
    AGENCE_LOCALE_DE_L_ENERGIE_ET_DU_CLIMAT_DE_PLAINE_COMMUNE("[mo_prefix_code]_agence_locale_de_l_energie_et_du_climat_de_plaine_commune", "Agence Locale de l’Energie et du Climat de Plaine Commune"),
    AGGLOMERATION_DE_SENART("[mo_prefix_code]_agglomeration_de_senart", "Agglomération de Sénart"),
    ALE("[mo_prefix_code]_ale", "ALE"),
    ALEC("[mo_prefix_code]_alec", "ALEC"),
    ALTERN_MOBIL("[mo_prefix_code]_altern_mobil", "Altern Mobil"),
    AMME("[mo_prefix_code]_amme", "AMME"),
    AQUITANIS_OPH_DE_BORDEAUX_METROPOLE("[mo_prefix_code]_aquitanis_oph_de_bordeaux_metropole", "Aquitanis - OPH de Bordeaux Métropole"),
    ARKHENSPACES("[mo_prefix_code]_arkhenspaces", "Arkhenspaces"),
    ARTELIA("[mo_prefix_code]_artelia", "Artelia"),
    ASF("[mo_prefix_code]_asf", "ASF"),
    ASSOCIATION_BELLASTOCK("[mo_prefix_code]_association_bellastock", "Association Bellastock"),
    ASSOCIATION_COMPAGNIE_MELIADES("[mo_prefix_code]_association_compagnie_meliades", "Association Compagnie Meliades"),
    ASSOCIATION_CONCHA("[mo_prefix_code]_association_concha", "Association Concha"),
    ASSOCIATION_DDAYS("[mo_prefix_code]_association_ddays", "Association DDAys"),
    ASSOCIATION_HALAGE("[mo_prefix_code]_association_halage", "Association Halage"),
    ASSOCIATION_HIASMA("[mo_prefix_code]_association_hiasma", "Association Hiasma"),
    ASSOCIATION_KHIASMA("[mo_prefix_code]_association_khiasma", "Association Khiasma"),
    ASSOCIATION_PAYSAN_URBAIN("[mo_prefix_code]_association_paysan_urbain", "Association Paysan urbain"),
    ASSOCIATION_PLAINE_COWORKING("[mo_prefix_code]_association_plaine_coworking", "Association Plaine Coworking"),
    ASSOCIATIONS_D_USAGERS("[mo_prefix_code]_associations_d_usagers", "Associations d’usagers"),
    ATOS_WORLDGRID_SAS("[mo_prefix_code]_atos_worldgrid_sas", "ATOS Worldgrid SAS"),
    BORDEAUX("[mo_prefix_code]_bordeaux", "Bordeaux"),
    BORDEAUX_METROPOLE("[mo_prefix_code]_bordeaux_metropole", "Bordeaux Métropole"),
    BOUYGUES("[mo_prefix_code]_bouygues", "Bouygues"),
    BOUYGUES_CONSTRUCTION("[mo_prefix_code]_bouygues_construction", "Bouygues Construction"),
    BOUYGUES_IMMOBILIER("[mo_prefix_code]_bouygues_immobilier", "Bouygues Immobilier"),
    BREST_METROPOLE("[mo_prefix_code]_brest_metropole", "Brest Métropole"),
    BREST_METROPOLE_AMANEGEMENT("[mo_prefix_code]_brest_metropole_amanegement", "Brest Métropole Amanégement"),
    BRIGITTE_PHILIPPON_JKALT_SARL_ARCHITECT("[mo_prefix_code]_brigitte_philippon_jkalt_sarl_architect", "Brigitte Philippon J.Kalt SARL Architect"),
    CA2_RS("[mo_prefix_code]_ca2_rs", "CA2RS"),
    CAMPUS_CONDORCET_ET_EPFIF("[mo_prefix_code]_campus_condorcet_et_epfif", "Campus Condorcet et EPFIF"),
    CARENE_SAINT_NAZAIRE_AGGLOMERATION("[mo_prefix_code]_carene_saint_nazaire_agglomeration", "CARENE Saint-Nazaire agglomération"),
    CCIAG("[mo_prefix_code]_cciag", "CCIAG"),
    CCPHVA("[mo_prefix_code]_ccphva", "CCPHVA"),
    CENTRE_MICHEL_SERRES("[mo_prefix_code]_centre_michel_serres", "Centre Michel Serres"),
    CESSON_SEVIGNE("[mo_prefix_code]_cesson_sevigne", "Cesson Sévigné"),
    CHOISY_LE_ROI("[mo_prefix_code]_choisy_le_roi", "Choisy-le-Roi"),
    CITELUM("[mo_prefix_code]_citelum", "Citelum"),
    CLERMONT_COMMUNAUTE("[mo_prefix_code]_clermont_communaute", "Clermont Communauté"),
    CLERMONT_FERRAND("[mo_prefix_code]_clermont_ferrand", "Clermont-Ferrand"),
    CNRS("[mo_prefix_code]_cnrs", "CNRS"),
    COGEDIM_GRENOBLE("[mo_prefix_code]_cogedim_grenoble", "Cogedim Grenoble"),
    COLLECTIF_D_ASSOCIATIONS_LOCALES_POUR_LA_TRANSITION_ECOLOGIQUE("[mo_prefix_code]_collectif_d_associations_locales_pour_la_transition_ecologique", "Collectif d’associations locales pour la transition écologique"),
    COLLECTIFS_D_ARTISTES("[mo_prefix_code]_collectifs_d_artistes", "Collectifs d’artistes"),
    COLLECTIVITES_NANTES_METROPOLE("[mo_prefix_code]_collectivites_nantes_metropole", "Collectivités Nantes Métropole"),
    COMMISSARIAT_A_L_ENERGIE_ATOMIQUE_ET_AUX_ENERGIES_ALTERNATIVES("[mo_prefix_code]_commissariat_a_l_energie_atomique_et_aux_energies_alternatives", "Commissariat à l'énergie atomique et aux énergies alternatives"),
    COMMUNAUTE_D_AGGLOMERATION_ROISSY_PAYS_DE_FRANCE("[mo_prefix_code]_communaute_d_agglomeration_roissy_pays_de_france", "Communauté d’agglomération Roissy Pays de France"),
    COMMUNAUTE_D_AGGLOMERATION_SEINE_VEXIN("[mo_prefix_code]_communaute_d_agglomeration_seine_vexin", "Communauté d’agglomération Seine&Vexin"),
    COMMUNAUTE_D_AGGLOMERATION_PLAINE_COMMUNE("[mo_prefix_code]_communaute_d_agglomeration_plaine_commune", "Communaute d'agglomération Plaine Commune"),
    COMMUNAUTE_D_AGGLOMERATION_REGION_NAZARIENNE_ET_ESTUAIRE("[mo_prefix_code]_communaute_d_agglomeration_region_nazarienne_et_estuaire", "Communaute d'agglomération région nazarienne et estuaire"),
    COMMUNAUTE_D_AGGLOMERATION_SEINE_AMONT("[mo_prefix_code]_communaute_d_agglomeration_seine_amont", "Communaute d'agglomération Seine Amont"),
    COMMUNAUTE_D_AGGLOMERATION_TERRITOIRE_COTE_OUEST("[mo_prefix_code]_communaute_d_agglomeration_territoire_cote_ouest", "Communauté d'Agglomération Territoire Côte Ouest"),
    COMMUNAUTE_DE_COMMUNES_DU_PAYS_HAUT_VAL_D_ALZETTE("[mo_prefix_code]_communaute_de_communes_du_pays_haut_val_d_alzette", "Communauté de communes du Pays Haut Val d'Alzette"),
    COMMUNAUTE_DE_COMMUNES_LOIRE_ET_SILLON("[mo_prefix_code]_communaute_de_communes_loire_et_sillon", "Communauté de communes Loire et Sillon"),
    COMMUNAUTE_PARIS_SACLAY("[mo_prefix_code]_communaute_paris_saclay", "Communauté Paris-Saclay (91)"),
    COMMUNAUTE_URBAINE_CLERMONT_AUVERGNE_METROPOLE("[mo_prefix_code]_communaute_urbaine_clermont_auvergne_metropole", "Clermont Auvergne Métropole"),
    COMMUNAUTE_URBAINE_DE_LYON("[mo_prefix_code]_communaute_urbaine_de_lyon", "Communauté urbaine de Lyon"),
    COMMUNAUTE_URBAINE_MARSEILLE_PROVENCE_METROPOLE("[mo_prefix_code]_communaute_urbaine_marseille_provence_metropole", "Communauté urbaine Marseille Provence Métropole"),
    COMMUNAUTE_URBAINE_NICE_COTE_D_AZUR("[mo_prefix_code]_communaute_urbaine_nice_cote_d_azur", "Communauté urbaine Nice Côte d'Azur"),
    COMMUNES_CONCERNEES_DE_L_ETABLISSEMENT_PUBLIC_TERRITORIAL_PARIS_OUEST_LA_DEFENSE("[mo_prefix_code]_communes_concernees_de_l_etablissement_public_territorial_paris_ouest_la_defense", "Communes concernées de l'Etablissement public territorial Paris Ouest la Défense"),
    COMMUNES_DE_SEINE_VEXIN("[mo_prefix_code]_communes_de_seine_vexin", "Communes de Seine&Vexin"),
    COMPAGNIE_DE_CHAUFFAGE_INTERCOMMUNALE_DE_L_AGGLOMERATION_GRENOBLOISE("[mo_prefix_code]_compagnie_de_chauffage_intercommunale_de_l_agglomeration_grenobloise", "Compagnie de chauffage intercommunale de l'Agglomération Grenobloise"),
    COMPAGNIE_DES_TRANSPORTS_STRASBOURGEOIS("[mo_prefix_code]_compagnie_des_transports_strasbourgeois", "Compagnie des transports strasbourgeois"),
    CONCEPTO("[mo_prefix_code]_concepto", "Concepto"),
    CONSEIL_DEPARTEMENTAL_DU_VAL_DE_MARNE("[mo_prefix_code]_conseil_departemental_du_val_de_marne", "Conseil départemental du Val de Marne"),
    CONSEIL_REGIONAL("[mo_prefix_code]_conseil_regional", "Conseil régional"),
    CONSERVATOIRE_DES_ESPACES_NATURELS_D_AUVERGNE("[mo_prefix_code]_conservatoire_des_espaces_naturels_d_auvergne", "Conservatoire des Espaces Naturels d’Auvergne"),
    CREDIT_COOPERATIF("[mo_prefix_code]_credit_cooperatif", "Crédit cooperatif"),
    CROUS("[mo_prefix_code]_crous", "CROUS"),
    CSTB("[mo_prefix_code]_cstb", "CSTB"),
    DESIGNERS_DAYS("[mo_prefix_code]_designers_days", "Designers days"),
    DRAC("[mo_prefix_code]_drac", "DRAC"),
    ECO_ENTREPRISE_POUR_L_INNOVATION_EN_AUVERGNE("[mo_prefix_code]_eco_entreprise_pour_l_innovation_en_auvergne", "Eco entreprise pour l'innovation en Auvergne"),
    ECOLE_DES_INGENIEURS_DE_LA_VILLE_DE_PARIS("[mo_prefix_code]_ecole_des_ingenieurs_de_la_ville_de_paris", "Ecole des Ingénieurs de la Ville de Paris"),
    ECOLE_SUPERIEURE_D_ARTS_ET_DESIGN("[mo_prefix_code]_ecole_superieure_d_arts_et_design", "Ecole Supérieure d’Arts et Design (ESAD TPM)"),
    ECOLES_D_ART_ET_D_ARCHITECTURE("[mo_prefix_code]_ecoles_d_art_et_d_architecture", "Ecoles d’art et d’architecture"),
    EDF("[mo_prefix_code]_edf", "EDF"),
    EFFICACITY("[mo_prefix_code]_efficacity", "Efficacity"),
    EGIDIA("[mo_prefix_code]_egidia", "Egidia"),
    EIFFAGE("[mo_prefix_code]_eiffage", "Eiffage"),
    ELITHIS("[mo_prefix_code]_elithis", "Elithis"),
    EMMAUS_HABITAT("[mo_prefix_code]_emmaus_habitat", "Emmaüs habitat"),
    ENERGIES_DU_SUD("[mo_prefix_code]_energies_du_sud", "Energies du Sud"),
    ENGIE("[mo_prefix_code]_engie", "ENGIE"),
    ENSE3_G2_ELAB("[mo_prefix_code]_ense3_g2_elab", "ENSE3/G2ELAB"),
    EPA_ALZETTE_BELVAL("[mo_prefix_code]_epa_alzette_belval", "EPA Alzette Belval"),
    EPA_ALZETTE_BELVAL_AVEC_LA_COMMUNAUTE_DE_COMMUNES_DU_PAYS_DU_HAUT_VAL_D_ALZETTE("[mo_prefix_code]_epa_alzette_belval_avec_la_communaute_de_communes_du_pays_du_haut_val_d_alzette", "EPA Alzette-Belval, avec la Communauté de Communes du Pays du Haut Val d’Alzette"),
    EPA_BORDEAUX_EURATLANTIQUE("[mo_prefix_code]_epa_bordeaux_euratlantique", "EPA Bordeaux Euratlantique"),
    EPA_DEFENSE_SEINE_ARCHE("[mo_prefix_code]_epa_defense_seine_arche", "EPA Défense Seine Arche (EPADESA)"),
    EPA_EUROMEDITERRANEE("[mo_prefix_code]_epa_euromediterranee", "EPA Euroméditerranée"),
    EPA_MANTOIS_SEINE_AVAL("[mo_prefix_code]_epa_mantois_seine_aval", "EPA Mantois Seine Aval (EPAMSA)"),
    EPA_MARNE_LA_VALLEE("[mo_prefix_code]_epa_marne_la_vallee", "EPA Marne-la-Vallée (EPAMARNE)"),
    EPA_ORLY_RUNGIS_SEINE_AMONT("[mo_prefix_code]_epa_orly_rungis_seine_amont", "EPA Orly-Rungis-Seine Amont (EPA ORSA)"),
    EPA_ORLY_RUNGIS_SEINE_AMONT_ET_ETABLISSEMENT_PUBLIC_TERRITORIAL_EPT12("[mo_prefix_code]_epa_orly_rungis_seine_amont_et_etablissement_public_territorial_ept12", "EPA Orly-Rungis-Seine Amont (EPA ORSA) et Etablissement public territorial EPT 12"),
    EPA_PARIS_SACLAY("[mo_prefix_code]_epa_paris_saclay", "EPA Paris-Saclay"),
    EPA_PLAINE_DE_FRANCE("[mo_prefix_code]_epa_plaine_de_france", "EPA Plaine de France"),
    EPA_PLAINE_DU_VAR("[mo_prefix_code]_epa_plaine_du_var", "EPA Plaine du Var"),
    EPA_SENART("[mo_prefix_code]_epa_senart", "EPA Sénart"),
    EPF_PACA("[mo_prefix_code]_epf_paca", "EPF PACA"),
    EPFL("[mo_prefix_code]_epfl", "EPFL"),
    ETABLISSEMENT_PUBLIC_FONCIER_DE_LORRAINE("[mo_prefix_code]_etablissement_public_foncier_de_lorraine", "Etablissement Public foncier de Lorraine"),
    ETABLISSEMENT_PUBLIC_TERRITORIAL_EST_ENSEMBLE("[mo_prefix_code]_etablissement_public_territorial_est_ensemble", "Etablissement Public Territorial Est Ensemble (EPT 8)"),
    ETABLISSEMENT_PUBLIC_TERRITORIAL_PARIS_OUEST_LA_DEFENSE("[mo_prefix_code]_etablissement_public_territorial_paris_ouest_la_defense", "Établissement Public Territorial Paris Ouest La Défense (EPT 4)"),
    ETABLISSEMENT_PUBLIC_TERRITORIAL_PLAINE_COMMUNE("[mo_prefix_code]_etablissement_public_territorial_plaine_commune", "Etablissement Public Territorial Plaine Commune (EPT 6)"),
    ETOILE_DE_NOMENY_SOCIETE_CIVILE_COOPERATIVE_DE_CONSTRUCTION("[mo_prefix_code]_etoile_de_nomeny_societe_civile_cooperative_de_construction", "Etoile de Nomeny Société civile coopérative de construction"),
    EUROMETROPOLE_DE_STRASBOURG("[mo_prefix_code]_eurometropole_de_strasbourg", "Eurométropole de Strasbourg"),
    FOYER_REMOIS("[mo_prefix_code]_foyer_remois", "Foyer Rémois"),
    FRESHMILE("[mo_prefix_code]_freshmile", "Freshmile"),
    FULTON("[mo_prefix_code]_fulton", "Fulton"),
    GDSOL_KAPPA("[mo_prefix_code]_gdsol_kappa", "GDSOL KAPPA"),
    GEG_GAZ_ET_ELECTRICITE_DE_GRENOBLE("[mo_prefix_code]_geg_gaz_et_electricite_de_grenoble", "GEG Gaz et Electricité de Grenoble"),
    GIRONDE_HABITAT("[mo_prefix_code]_gironde_habitat", "Gironde Habitat"),
    GRAND_LYON_HABITAT("[mo_prefix_code]_grand_lyon_habitat", "Grand Lyon Habitat"),
    GRAND_ORLY_VAL_DE_BIEVRE_SEINE_AMONT_T12("[mo_prefix_code]_grand_orly_val_de_bievre_seine_amont_t12", "Grand Orly Val de Bièvre Seine Amont T12"),
    GRAND_PORT_MARITIME_DE_ROUEN("[mo_prefix_code]_grand_port_maritime_de_rouen", "Grand Port Maritime de Rouen"),
    GRENOBLE("[mo_prefix_code]_grenoble", "Grenoble"),
    GRENOBLE_ALPES_METROPOLE("[mo_prefix_code]_grenoble_alpes_metropole", "Grenoble Alpes Métropole"),
    GRENOBLE_HABITAT("[mo_prefix_code]_grenoble_habitat", "Grenoble Habitat"),
    GRENOBLE_INP("[mo_prefix_code]_grenoble_inp", "Grenoble INP"),
    GROUPE3_F("[mo_prefix_code]_groupe3_f", "Groupe 3F"),
    HABITAT_DE_L_ILL("[mo_prefix_code]_habitat_de_l_ill", "Habitat de l’Ill"),
    HERAULT_TRANSPORT("[mo_prefix_code]_herault_transport", "Hérault Transport"),
    HESPUL("[mo_prefix_code]_hespul", "Hespul"),
    HOLTZHEIM("[mo_prefix_code]_holtzheim", "Holtzheim"),
    HYDREOS_ILOT_AENERGIE_POSITIVE_MICHEVILLE_NON_DESIGNE("[mo_prefix_code]_hydreos_ilot_aenergie_positive_micheville_non_designe", "Hydréos : ilot à énergie positive Micheville non désigné (Groupe Linkcity pressenti)"),
    ICADE_PROMOTION_LOGEMENT("[mo_prefix_code]_icade_promotion_logement", "Icade Promotion Logement"),
    IFSTTAR("[mo_prefix_code]_ifsttar", "IFSTTAR"),
    INSTITUT_VEDECOM("[mo_prefix_code]_institut_vedecom", "Institut VEDECOM"),
    ISERE_HABITAT("[mo_prefix_code]_isere_habitat", "Isère habitat"),
    IVRY_SUR_SEINE("[mo_prefix_code]_ivry_sur_seine", "Ivry-sur-Seine"),
    KEYS_EURATLANTIQUE("[mo_prefix_code]_keys_euratlantique", "Keys Euratlantique"),
    KYOMED("[mo_prefix_code]_kyomed", "KYOMED"),
    L_ATELIER_EARTH_AVOCATS("[mo_prefix_code]_l_atelier_earth_avocats", "L’Atelier – Earth Avocats"),
    LA_FABRIQUE_POLA("[mo_prefix_code]_la_fabrique_pola", "La fabrique Pola"),
    LA_POSSESSION("[mo_prefix_code]_la_possession", "La Possession"),
    LA_POSTE("[mo_prefix_code]_la_poste", "La Poste"),
    LABORATOIRES_DE_RECHERCHE("[mo_prefix_code]_laboratoires_de_recherche", "Laboratoires de recherche (LICIT / IFSTTAR …)"),
    L_AIR_LIQUIDE_SA_POUR_L_ETUDE_ET_L_EXPLOITATION_DES_PROCEDES_GEORGES_CLAUDE("[mo_prefix_code]_l_air_liquide_sa_pour_l_etude_et_l_exploitation_des_procedes_georges_claude", "L'air liquide SA pour l'étude et l'exploitation des procédés Georges Claude"),
    LE_FOYER_DE_L_ISERE("[mo_prefix_code]_le_foyer_de_l_isere", "Le foyer de l'Isère"),
    LILLE("[mo_prefix_code]_lille", "Lille"),
    LINKCITY_ILE_DE_FRANCE("[mo_prefix_code]_linkcity_ile_de_france", "Linkcity Ile de france"),
    LYON_CONFLUENCE("[mo_prefix_code]_lyon_confluence", "Lyon Confluence"),
    MANUFACTURE_MICHELIN("[mo_prefix_code]_manufacture_michelin", "Manufacture Michelin"),
    MARCHE_D_INTERET_NATIONAL_DE_BRIENNE("[mo_prefix_code]_marche_d_interet_national_de_brienne", "Marché d’intérêt national de Brienne"),
    MARSEILLE("[mo_prefix_code]_marseille", "Marseille"),
    MELIADES("[mo_prefix_code]_meliades", "Meliades"),
    METROPOLE_AIX_MARSEILLE_PROVENSE("[mo_prefix_code]_metropole_aix_marseille_provense", "Métropole Aix Marseille Provense"),
    METROPOLE_DE_LYON("[mo_prefix_code]_metropole_de_lyon", "Métropole de Lyon (Grand Lyon)"),
    METROPOLE_EUROPEENNE_DE_LILLE("[mo_prefix_code]_metropole_europeenne_de_lille", "Métropole Européenne de Lille"),
    METROPOLE_NANTES_METROPOLE("[mo_prefix_code]_metropole_nantes_metropole", "Métropole Nantes-Métropole"),
    METROPOLE_NICE_COTE_D_AZUR("[mo_prefix_code]_metropole_nice_cote_d_azur", "Métropole Nice Côte d’Azur"),
    METROPOLE_ROUEN_NORMANDIE("[mo_prefix_code]_metropole_rouen_normandie", "Metropole Rouen Normandie"),
    METZ_METROPOLE("[mo_prefix_code]_metz_metropole", "Metz Métropole"),
    METZ_METROPOLE_DEVELOPPEMENT("[mo_prefix_code]_metz_metropole_developpement", "Metz Métropole Développement"),
    MICHELIN_MANUFACTURE_FRANCAISE_DES_PNEUMATIQUES_SCA("[mo_prefix_code]_michelin_manufacture_francaise_des_pneumatiques_sca", "Michelin - Manufacture francaise des pneumatiques sca"),
    MIXENER_SAS("[mo_prefix_code]_mixener_sas", "Mixener SAS"),
    MO_SYSTEME_IMMOTIQUE_ET_SERVICES_DE_MAINTIEN_ADOMICILE_NON_IDENTIFIE("[mo_prefix_code]_mo_systeme_immotique_et_services_de_maintien_adomicile_non_identifie", "MO Système immotique et services de maintien à domicile non identifié"),
    MONTFERMEIL("[mo_prefix_code]_montfermeil", "Montfermeil"),
    MONTPELLIER("[mo_prefix_code]_montpellier", "Montpellier"),
    MONTPELLIER_MEDITERRANEE_METROPOLE("[mo_prefix_code]_montpellier_mediterranee_metropole", "Montpellier Méditerranée Métropole"),
    MUNDGAWI("[mo_prefix_code]_mundgawi", "Mundgawi"),
    NANTERRE("[mo_prefix_code]_nanterre", "Nanterre"),
    NANTES_METROPOLE_AMENAGEMENT("[mo_prefix_code]_nantes_metropole_amenagement", "Nantes Métropole Aménagement"),
    NEOPOLIA("[mo_prefix_code]_neopolia", "Neopolia"),
    NOUVEL_HABITAT("[mo_prefix_code]_nouvel_habitat", "Nouvel Habitat"),
    OFFICE_PUBLIC_HABITAT_PARIS_HABITAT("[mo_prefix_code]_office_public_habitat_paris_habitat", "Office public habitat - Paris habitat"),
    OPPIDEA("[mo_prefix_code]_oppidea", "Oppidea"),
    PARIS("[mo_prefix_code]_paris", "Paris"),
    PAYSAN_URBAIN("[mo_prefix_code]_paysan_urbain", "Paysan urbain"),
    PETR_DU_GRAND_CLERMONT("[mo_prefix_code]_petr_du_grand_clermont", "PETR du Grand Clermont"),
    PIERRES_ET_TERRITOIRES_DE_FRANCE_ALSACE("[mo_prefix_code]_pierres_et_territoires_de_france_alsace", "Pierres et territoires de France Alsace"),
    PLATEFORME_DE_SERVICES_NOE("[mo_prefix_code]_plateforme_de_services_noe", "Plateforme de services NOE"),
    POLE_DE_COMPETITIVITE_FIBRES_ENERGIVIE("[mo_prefix_code]_pole_de_competitivite_fibres_energivie", "Pôle de compétitivité Fibres-Energivie"),
    POLE_METROPOLITAIN_NANTES_ST_NAZAIRE("[mo_prefix_code]_pole_metropolitain_nantes_st_nazaire", "Pole métropolitain Nantes St-Nazaire"),
    POLE_UTILITE_SERVICES("[mo_prefix_code]_pole_utilite_services", "Pôle Utilité Services"),
    PORT_AUTONOME_DE_STRASBOURG("[mo_prefix_code]_port_autonome_de_strasbourg", "Port autonome de Strasbourg"),
    POSTE_IMMO("[mo_prefix_code]_poste_immo", "Poste Immo"),
    PROMOTION_PICHET("[mo_prefix_code]_promotion_pichet", "Promotion Pichet"),
    RATP("[mo_prefix_code]_ratp", "RATP"),
    RECTORAT("[mo_prefix_code]_rectorat", "Rectorat"),
    RENNES("[mo_prefix_code]_rennes", "Rennes"),
    RENNES_METROPOLE("[mo_prefix_code]_rennes_metropole", "Rennes Métropole"),
    RIVP("[mo_prefix_code]_rivp", "RIVP"),
    ROUEN("[mo_prefix_code]_rouen", "Rouen"),
    RUEIL_MALMAISON("[mo_prefix_code]_rueil_malmaison", "Rueil-Malmaison"),
    RUF("[mo_prefix_code]_ruf", "RUF"),
    SAMOA_SOCIETE_D_AMENAGEMENT_DE_LA_METROPOLE_OUEST_ATLANTIQUE("[mo_prefix_code]_samoa_societe_d_amenagement_de_la_metropole_ouest_atlantique", "S.A.M.O.A. Société d'Aménagement de la Métropole Ouest Atlantique"),
    SAEM_DE_RENOVATION_ET_DE_RESTAURATION_DE_LILLE("[mo_prefix_code]_saem_de_renovation_et_de_restauration_de_lille", "SAEM de rénovation et de restauration de Lille"),
    SAINT_QUENTIN_EN_YVELINES("[mo_prefix_code]_saint_quentin_en_yvelines", "Saint-Quentin-en-Yvelines (78)"),
    SAS_ALLAR_C("[mo_prefix_code]_sas_allar_c", "SAS Allar C"),
    SAS_BASTIDE_NIEL("[mo_prefix_code]_sas_bastide_niel", "SAS Bastide-Niel"),
    SAS_ENERGIE_DES_BASSINS("[mo_prefix_code]_sas_energie_des_bassins", "SAS énergie des bassins"),
    SCCV_LE_PYTHON("[mo_prefix_code]_sccv_le_python", "SCCV Le Python"),
    SCCV_TIGERY_ARTENOVA("[mo_prefix_code]_sccv_tigery_artenova", "SCCV Tigery Artenova"),
    SCI_GREEN_ONE("[mo_prefix_code]_sci_green_one", "SCI Green One"),
    SCI_PI_BORDEAUX_TOURVILLE("[mo_prefix_code]_sci_pi_bordeaux_tourville", "SCI PI Bordeaux Tourville"),
    SEDRE("[mo_prefix_code]_sedre", "SEDRE"),
    SELAS_ROCHELOIS_BESINS_ET_ASSOCIES("[mo_prefix_code]_selas_rochelois_besins_et_associes", "Selas Rochelois-Besins et associés"),
    SEM_INNO_VIA("[mo_prefix_code]_sem_inno_via", "SEM InnoVia"),
    SEM_PLAINE_COMMUNE_DEVELOPPEMENT("[mo_prefix_code]_sem_plaine_commune_developpement", "SEM Plaine Commune développement"),
    SEM_VILLE_RENOUVELEE("[mo_prefix_code]_sem_ville_renouvelee", "SEM Ville renouvelée"),
    SEMADER("[mo_prefix_code]_semader", "SEMADER"),
    SEQUANO_AMENAGEMENT("[mo_prefix_code]_sequano_amenagement", "Séquano aménagement"),
    SERM("[mo_prefix_code]_serm", "SERM"),
    SETEC("[mo_prefix_code]_setec", "SETEC"),
    SHAMENGO("[mo_prefix_code]_shamengo", "Shamengo"),
    SM_SCOT_METROPOLE_NANTES_ST_NAZAIRE("[mo_prefix_code]_sm_scot_metropole_nantes_st_nazaire", "SM Scot Métropole Nantes St Nazaire"),
    SMART_LIGHTING_ALLIANCE("[mo_prefix_code]_smart_lighting_alliance", "Smart lighting alliance"),
    SNCF("[mo_prefix_code]_sncf", "SNCF"),
    SOC_COOP_HABITATION_LOYER_MODERE("[mo_prefix_code]_soc_coop_habitation_loyer_modere", "SOC COOP habitation loyer modere"),
    SOCIETE_D_AMENAGEMENT_ET_D_EQUIPEMENT_DE_LA_REGION_DE_STRASBOURG("[mo_prefix_code]_societe_d_amenagement_et_d_equipement_de_la_region_de_strasbourg", "Société d'aménagement et d'équipement de la région de Strasbourg"),
    SOCIETE_D_EQUIPEMENT_DE_LA_REGION_MONTPELLIERAINE("[mo_prefix_code]_societe_d_equipement_de_la_region_montpellieraine", "Société d'équipement de la région montpellieraine"),
    SOCIETE_D_HABITATION_DES_ALPES_SAHLM("[mo_prefix_code]_societe_d_habitation_des_alpes_sahlm", "Société d'habitation des Alpes SAHLM"),
    SOCIETE_DU_GRAND_PARIS("[mo_prefix_code]_societe_du_grand_paris", "Société du Grand Paris"),
    SOCIETE_LIGIER_AUTOMOBILES("[mo_prefix_code]_societe_ligier_automobiles", "Société Ligier automobiles"),
    SOCIETE_PUBLIQUE_LOCALE_DEUX_RIVES("[mo_prefix_code]_societe_publique_locale_deux_rives", "Société publique locale deux rives"),
    SODEARIF("[mo_prefix_code]_sodearif", "Sodéarif"),
    SOGARIS("[mo_prefix_code]_sogaris", "Sogaris"),
    SOGARIS_PARIS_LES_ESPACES_LOGISTIQUES_URBAINS("[mo_prefix_code]_sogaris_paris_les_espaces_logistiques_urbains", "Sogaris Paris les espaces logistiques urbains"),
    SOL_PAYSAGE("[mo_prefix_code]_sol_paysage", "Sol Paysage"),
    SONADEV("[mo_prefix_code]_sonadev", "SONADEV"),
    SONADEV_TERRITOIRES_PUBLICS("[mo_prefix_code]_sonadev_territoires_publics", "SONADEV territoires publics"),
    SORELI("[mo_prefix_code]_soreli", "SORELI"),
    SOUKMACHINES("[mo_prefix_code]_soukmachines", "Soukmachines"),
    SPIE("[mo_prefix_code]_spie", "SPIE"),
    SPL_DEUX_RIVES("[mo_prefix_code]_spl_deux_rives", "SPL Deux Rives"),
    SPL_EURALILLE("[mo_prefix_code]_spl_euralille", "SPL Euralille"),
    SPL_LYON_CONFLUENCE("[mo_prefix_code]_spl_lyon_confluence", "SPL Lyon Confluence"),
    SPL_LYON_PARTDIEU("[mo_prefix_code]_spl_lyon_partdieu", "SPL Lyon Partdieu"),
    SPL_ROUEN_NORMANDIE_AMENAGEMENT("[mo_prefix_code]_spl_rouen_normandie_amenagement", "SPL Rouen Normandie Aménagement"),
    SPLA_SAGES("[mo_prefix_code]_spla_sages", "SPLA SAGES"),
    SPLA_TERRITOIRES_PUBLICS("[mo_prefix_code]_spla_territoires_publics", "SPLA Territoires publics"),
    SPLA_VIASILVA("[mo_prefix_code]_spla_viasilva", "SPLA Viasilva"),
    STATION_FRENCH_TECH("[mo_prefix_code]_station_french_tech", "Station French Tech"),
    STIF("[mo_prefix_code]_stif", "STIF"),
    STRASBOURG("[mo_prefix_code]_strasbourg", "Strasbourg"),
    STX_CABINS("[mo_prefix_code]_stx_cabins", "STX cabins"),
    SUSTAINABLE_URBAN_DESIGN_STRATEGY("[mo_prefix_code]_sustainable_urban_design_strategy", "Sustainable Urban Design Strategy (SUDS)"),
    SYNDICAT_INTERCOMMUNAL_DES_TRANSPORTS_EN_COMMUN_DE_L_AGGLOMERATION_CLERMONTOISE("[mo_prefix_code]_syndicat_intercommunal_des_transports_en_commun_de_l_agglomeration_clermontoise", "Syndicat intercommunal des transports en commun de l'agglomération Clermontoise"),
    SYNDICAT_INTERCOMMUNAL_POUR_L_AMENAGEMENT_HYDRAULIQUE_DES_VALLEES_DU_CROULT_ET_DU_PETIT_ROSNE("[mo_prefix_code]_syndicat_intercommunal_pour_l_amenagement_hydraulique_des_vallees_du_croult_et_du_petit_rosne", "Syndicat Intercommunal pour l'Aménagement Hydraulique des vallées du Croult et du Petit Rosne (SIAH)"),
    SYNDICAT_MIXTE_DES_TRANSPORTS_EN_COMMUN_DE_L_AGGLOMERATION_CLERMONTOISE("[mo_prefix_code]_syndicat_mixte_des_transports_en_commun_de_l_agglomeration_clermontoise", "Syndicat mixte des transports en commun de l'agglomération clermontoise"),
    SYNDICAT_MIXTE_DES_TRANSPORTS_EN_COMMUN_DE_L_AGGLOMERATION_TOULOUSAINE("[mo_prefix_code]_syndicat_mixte_des_transports_en_commun_de_l_agglomeration_toulousaine", "Syndicat mixte des transports en commun de l'agglomération toulousaine"),
    SYNDICAT_MIXTE_POUR_LA_GESTION_ET_L_INCINERATION_DES_DECHETS_MENAGERS_DE_LA_REGION_DE_SARCELLES("[mo_prefix_code]_syndicat_mixte_pour_la_gestion_et_l_incineration_des_dechets_menagers_de_la_region_de_sarcelles", "Syndicat Mixte pour la Gestion et l’Incinération des Déchets Ménagers de la Région de Sarcelles (SIGIDURS)"),
    SYNDICAT_MIXTE_DES_TRANSPORTS_EN_COMMUN_DE_GRENOBLE("[mo_prefix_code]_syndicat_mixte_des_transports_en_commun_de_grenoble", "Syndicat mixte des transports en commun de Grenoble"),
    SYNDICAT_POUR_LA_VALORISATION_ET_LE_TRAITEMENT_DES_DECHETS("[mo_prefix_code]_syndicat_pour_la_valorisation_et_le_traitement_des_dechets", "Syndicat pour la valorisation et le traitement des déchets"),
    SYNDICATS_DE_COPROPRIETAIRES_ET_MAITRISE_D_OUVRE("[mo_prefix_code]_syndicats_de_coproprietaires_et_maitrise_d_ouvre", "Syndicats de copropriétaires et maîtrise d’œuvre"),
    SYSTRA("[mo_prefix_code]_systra", "SYSTRA"),
    TAM("[mo_prefix_code]_tam", "TAM"),
    TED_INVEST("[mo_prefix_code]_ted_invest", "Ted invest"),
    TENERRDIS("[mo_prefix_code]_tenerrdis", "Tenerrdis"),
    TERRITOIRE_DE_LA_COTE_OUEST("[mo_prefix_code]_territoire_de_la_cote_ouest", "Territoire de la Côte Ouest"),
    TERRITOIRES_ET_DEVELOPPEMENT_SOCIETE_D_AMENAGEMENT_DU_BASSIN_RENNAIS("[mo_prefix_code]_territoires_et_developpement_societe_d_amenagement_du_bassin_rennais", "Territoires et développement : Société d'aménagement du bassin rennais"),
    THORIGNE_FOUILLARD("[mo_prefix_code]_thorigne_fouillard", "Thorigné-Fouillard"),
    TOULON_PROVENCE_METROPOLE("[mo_prefix_code]_toulon_provence_metropole", "Toulon Provence Métropole"),
    TOULON_VAR_TECHNOLOGIE("[mo_prefix_code]_toulon_var_technologie", "Toulon Var Technologie (TVT)"),
    TOULOUSE("[mo_prefix_code]_toulouse", "Toulouse"),
    TOULOUSE_METROPOLE("[mo_prefix_code]_toulouse_metropole", "Toulouse Métropole"),
    TRANSDEV_GROUP("[mo_prefix_code]_transdev_group", "Transdev group"),
    UJF("[mo_prefix_code]_ujf", "UJF"),
    UNIVERSITE_PARIS_EST_MARNE_LA_VALLEE("[mo_prefix_code]_universite_paris_est_marne_la_vallee", "Université Paris Est Marne la Vallée"),
    UNIVERSITE_PARIS_SACLAY("[mo_prefix_code]_universite_paris_saclay", "Université Paris-Saclay"),
    USINE_D_ELECTRICITE_DE_METZ("[mo_prefix_code]_usine_d_electricite_de_metz", "Usine d’Electricité de Metz"),
    VEOLIA("[mo_prefix_code]_veolia", "Veolia"),
    VERSAILLES_GRAND_PARC("[mo_prefix_code]_versailles_grand_parc", "Versailles Grand Parc (78)"),
    VILLE_DU_PORT("[mo_prefix_code]_ville_du_port", "Ville du Port"),
    VITRY_SUR_SEINE("[mo_prefix_code]_vitry_sur_seine", "Vitry-sur-Seine"),
    VOIES_NAVIGABLES_DE_FRANCE("[mo_prefix_code]_voies_navigables_de_france", "Voies Navigables de France");

    static final String PREFIX = "[mo_prefix_code]_";

    String code;
    String libelle;

    MAITRISE_OUVRAGE(String code, String libelle) {
        this.code = code;
        this.libelle = libelle;
    }

    public static MAITRISE_OUVRAGE getByCode(String code)
    {
        if (code == null || !code.startsWith(PREFIX)) {
            return null;
        }
        for(MAITRISE_OUVRAGE enu : values())
        {
            if(enu.code.equals(code))
                return enu;
        }

        return null;
    }

    public static Optional<MAITRISE_OUVRAGE> getByCodeIfExist(String code)
    {
        return Optional.ofNullable(getByCode(code));
    }

    public static boolean isDefined(String code) {
        return code.startsWith(PREFIX) && getByCode(code) != null;
    }

    public static String getLibelleForCode(String code) {
        return getByCodeIfExist(code).map(MAITRISE_OUVRAGE::getLibelle).orElse(code);
    }

    public String getCode() {
        return code;
    }
    public String getLibelle() {
            return libelle;
        }
}
